/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.7.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as comments from "../comments.js";
import type * as cronJobRuns from "../cronJobRuns.js";
import type * as crons from "../crons.js";
import type * as fileTags from "../fileTags.js";
import type * as files from "../files.js";
import type * as filesActions from "../filesActions.js";
import type * as imageComparisons from "../imageComparisons.js";
import type * as lib_authorization from "../lib/authorization.js";
import type * as lib_relationships from "../lib/relationships.js";
import type * as lib_utils from "../lib/utils.js";
import type * as machineTokens from "../machineTokens.js";
import type * as migrations from "../migrations.js";
import type * as tags from "../tags.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  comments: typeof comments;
  cronJobRuns: typeof cronJobRuns;
  crons: typeof crons;
  fileTags: typeof fileTags;
  files: typeof files;
  filesActions: typeof filesActions;
  imageComparisons: typeof imageComparisons;
  "lib/authorization": typeof lib_authorization;
  "lib/relationships": typeof lib_relationships;
  "lib/utils": typeof lib_utils;
  machineTokens: typeof machineTokens;
  migrations: typeof migrations;
  tags: typeof tags;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
